version: '1.0'

services:
  backend:
    build: ./backend-jwt
    container_name: backend
    restart: always
    networks:
      - tea_network
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_SERVER: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mydb

  frontend:
      build: ./frontend-jwt
      container_name: frontend
      restart: always
      networks:
        - tea_network
      ports:
        - "80:80"
      depends_on:
        - backend

  database:
    container_name: database
    image: mysql:8
    restart: always
    networks:
      - tea_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          memory: '128M'
    ports:
      - '3308:3306'


networks:
  tea_network:
    driver: bridge


